Prueba/Controllers/PlanesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Prueba.Models;

namespace Prueba.Controllers
{
    public class PlanesController : Controller
    {
        private DBPrubas db = new DBPrubas();

        // GET: PPI_TBL_PLAN_PRUEBAS
        public ActionResult Index()
        {
            var pPI_TBL_PLAN_PRUEBAS = db.PPI_TBL_PLAN_PRUEBAS.Include(p => p.PPI_TBL_LIDER_PDS_PROYECTO).Include(p => p.PPI_TBL_LIDER_PDS_RESPONSABLE);
            return View(pPI_TBL_PLAN_PRUEBAS.ToList());
        }

        // GET: PPI_TBL_PLAN_PRUEBAS/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PPI_TBL_PLAN_PRUEBAS pPI_TBL_PLAN_PRUEBAS = db.PPI_TBL_PLAN_PRUEBAS.Find(id);
            if (pPI_TBL_PLAN_PRUEBAS == null)
            {
                return HttpNotFound();
            }
            return View(pPI_TBL_PLAN_PRUEBAS);
        }

        // GET: PPI_TBL_PLAN_PRUEBAS/Create
        public ActionResult Create()
        {
            ViewBag.LIDER_PDS_PROYECTO = new SelectList(db.PPI_TBL_LIDER_PDS, "ID_LIDER_PDS", "NOMBRE");
            ViewBag.LIDER_PDS_RESPONSABLE = new SelectList(db.PPI_TBL_LIDER_PDS, "ID_LIDER_PDS", "NOMBRE");
            return View();
        }

        // POST: PPI_TBL_PLAN_PRUEBAS/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_PRUEBAS,CODIGO_PROYECTO,LIDER_PDS_PROYECTO,LIDER_PDS_RESPONSABLE,FECHA_CREACION,FECHA_EVALUACION,FECHA_MODIFICACION,DESCRIPCION,DATOS_PRUEBA,CONCLUSIONES,MODULO,CREADO_POR,ESTADO")] PPI_TBL_PLAN_PRUEBAS pPI_TBL_PLAN_PRUEBAS)
        {
            if (ModelState.IsValid)
            {
                db.PPI_TBL_PLAN_PRUEBAS.Add(pPI_TBL_PLAN_PRUEBAS);
                db.SaveChanges();
                return RedirectToAction("Index");
                
            }

            ViewBag.LIDER_PDS_PROYECTO = new SelectList(db.PPI_TBL_LIDER_PDS, "ID_LIDER_PDS", "NOMBRE", pPI_TBL_PLAN_PRUEBAS.LIDER_PDS_PROYECTO);
            ViewBag.LIDER_PDS_RESPONSABLE = new SelectList(db.PPI_TBL_LIDER_PDS, "ID_LIDER_PDS", "NOMBRE", pPI_TBL_PLAN_PRUEBAS.LIDER_PDS_RESPONSABLE);
            return View(pPI_TBL_PLAN_PRUEBAS);
        }

        // GET: PPI_TBL_PLAN_PRUEBAS/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PPI_TBL_PLAN_PRUEBAS pPI_TBL_PLAN_PRUEBAS = db.PPI_TBL_PLAN_PRUEBAS.Find(id);
            if (pPI_TBL_PLAN_PRUEBAS == null)
            {
                return HttpNotFound();
            }
            ViewBag.LIDER_PDS_PROYECTO = new SelectList(db.PPI_TBL_LIDER_PDS, "ID_LIDER_PDS", "NOMBRE", pPI_TBL_PLAN_PRUEBAS.LIDER_PDS_PROYECTO);
            ViewBag.LIDER_PDS_RESPONSABLE = new SelectList(db.PPI_TBL_LIDER_PDS, "ID_LIDER_PDS", "NOMBRE", pPI_TBL_PLAN_PRUEBAS.LIDER_PDS_RESPONSABLE);
            return View(pPI_TBL_PLAN_PRUEBAS);
        }

        // POST: PPI_TBL_PLAN_PRUEBAS/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_PRUEBAS,CODIGO_PROYECTO,LIDER_PDS_PROYECTO,LIDER_PDS_RESPONSABLE,FECHA_CREACION,FECHA_EVALUACION,FECHA_MODIFICACION,DESCRIPCION,DATOS_PRUEBA,CONCLUSIONES,MODULO,CREADO_POR,ESTADO")] PPI_TBL_PLAN_PRUEBAS pPI_TBL_PLAN_PRUEBAS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pPI_TBL_PLAN_PRUEBAS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LIDER_PDS_PROYECTO = new SelectList(db.PPI_TBL_LIDER_PDS, "ID_LIDER_PDS", "NOMBRE", pPI_TBL_PLAN_PRUEBAS.LIDER_PDS_PROYECTO);
            ViewBag.LIDER_PDS_RESPONSABLE = new SelectList(db.PPI_TBL_LIDER_PDS, "ID_LIDER_PDS", "NOMBRE", pPI_TBL_PLAN_PRUEBAS.LIDER_PDS_RESPONSABLE);
            return View(pPI_TBL_PLAN_PRUEBAS);
        }

        // GET: PPI_TBL_PLAN_PRUEBAS/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PPI_TBL_PLAN_PRUEBAS pPI_TBL_PLAN_PRUEBAS = db.PPI_TBL_PLAN_PRUEBAS.Find(id);
            if (pPI_TBL_PLAN_PRUEBAS == null)
            {
                return HttpNotFound();
            }
            return View(pPI_TBL_PLAN_PRUEBAS);
        }

        // POST: PPI_TBL_PLAN_PRUEBAS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            PPI_TBL_PLAN_PRUEBAS pPI_TBL_PLAN_PRUEBAS = db.PPI_TBL_PLAN_PRUEBAS.Find(id);
            db.PPI_TBL_PLAN_PRUEBAS.Remove(pPI_TBL_PLAN_PRUEBAS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Prueba/Views/Planes/Create.cshtml
@model Prueba.Models.PPI_TBL_PLAN_PRUEBAS

@{
    ViewBag.Title = "Crear";
}

<h2>Crear nuevo plan</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CODIGO_PROYECTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CODIGO_PROYECTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CODIGO_PROYECTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LIDER_PDS_PROYECTO, "LIDER_PDS_PROYECTO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LIDER_PDS_PROYECTO", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LIDER_PDS_PROYECTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LIDER_PDS_RESPONSABLE, "LIDER_PDS_RESPONSABLE", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LIDER_PDS_RESPONSABLE", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LIDER_PDS_RESPONSABLE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_CREACION, htmlAttributes: new { @class = "control-label col-md-2"  })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_CREACION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_CREACION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_EVALUACION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_EVALUACION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_EVALUACION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_MODIFICACION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_MODIFICACION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_MODIFICACION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DESCRIPCION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DESCRIPCION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DESCRIPCION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATOS_PRUEBA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATOS_PRUEBA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATOS_PRUEBA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CONCLUSIONES, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CONCLUSIONES, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CONCLUSIONES, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MODULO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MODULO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MODULO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CREADO_POR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CREADO_POR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CREADO_POR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ESTADO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ESTADO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ESTADO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Prueba/Views/Planes/Delete.cshtml
@model Prueba.Models.PPI_TBL_PLAN_PRUEBAS

@{
    ViewBag.Title = "Delete";
}


<h3>Esta seguro que quiere eliminar este plan?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Lider PDS Proyecto")
            
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PPI_TBL_LIDER_PDS_PROYECTO.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayName("Lider PDS Responsable")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PPI_TBL_LIDER_PDS_RESPONSABLE.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CODIGO_PROYECTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CODIGO_PROYECTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_CREACION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_CREACION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_EVALUACION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_EVALUACION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_MODIFICACION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_MODIFICACION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DESCRIPCION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DESCRIPCION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATOS_PRUEBA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATOS_PRUEBA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CONCLUSIONES)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONCLUSIONES)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MODULO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MODULO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CREADO_POR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CREADO_POR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ESTADO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ESTADO)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>

Prueba/Views/Planes/Details.cshtml
@model Prueba.Models.PPI_TBL_PLAN_PRUEBAS

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>PPI_TBL_PLAN_PRUEBAS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PPI_TBL_LIDER_PDS_PROYECTO.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PPI_TBL_LIDER_PDS_PROYECTO.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PPI_TBL_LIDER_PDS_RESPONSABLE.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PPI_TBL_LIDER_PDS_RESPONSABLE.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CODIGO_PROYECTO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CODIGO_PROYECTO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_CREACION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_CREACION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_EVALUACION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_EVALUACION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FECHA_MODIFICACION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FECHA_MODIFICACION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DESCRIPCION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DESCRIPCION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DATOS_PRUEBA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DATOS_PRUEBA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CONCLUSIONES)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONCLUSIONES)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MODULO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MODULO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CREADO_POR)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CREADO_POR)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ESTADO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ESTADO)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_PRUEBAS }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Prueba/Views/Planes/Edit.cshtml
@model Prueba.Models.PPI_TBL_PLAN_PRUEBAS

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Plan</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_PRUEBAS)

        <div class="form-group">
            @Html.LabelFor(model => model.CODIGO_PROYECTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CODIGO_PROYECTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CODIGO_PROYECTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LIDER_PDS_PROYECTO, "LIDER_PDS_PROYECTO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LIDER_PDS_PROYECTO", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LIDER_PDS_PROYECTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LIDER_PDS_RESPONSABLE, "LIDER_PDS_RESPONSABLE", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LIDER_PDS_RESPONSABLE", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LIDER_PDS_RESPONSABLE, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_CREACION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_CREACION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_CREACION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_EVALUACION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_EVALUACION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_EVALUACION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FECHA_MODIFICACION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FECHA_MODIFICACION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FECHA_MODIFICACION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DESCRIPCION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DESCRIPCION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DESCRIPCION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DATOS_PRUEBA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DATOS_PRUEBA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DATOS_PRUEBA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CONCLUSIONES, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CONCLUSIONES, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CONCLUSIONES, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MODULO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MODULO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MODULO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CREADO_POR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CREADO_POR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CREADO_POR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ESTADO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ESTADO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ESTADO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Prueba/Views/Planes/Index.cshtml
@model IEnumerable<Prueba.Models.PPI_TBL_PLAN_PRUEBAS>

@{
    ViewBag.Title = "Index";
}

<h2>Listado de planes</h2>

<p>
    @Html.ActionLink("Crear nuevo plan", "Create")
</p>

<div class="table-responsive">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Lider PDS Proyecto")
            </th>
            <th>
                @Html.DisplayName("Lider PDS Responsable")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CODIGO_PROYECTO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FECHA_CREACION)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FECHA_EVALUACION)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FECHA_MODIFICACION)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DESCRIPCION)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DATOS_PRUEBA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CONCLUSIONES)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MODULO)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CREADO_POR)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ESTADO)
            </th>
            <th width="15%">Acciones</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PPI_TBL_LIDER_PDS_PROYECTO.NOMBRE)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PPI_TBL_LIDER_PDS_RESPONSABLE.NOMBRE)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CODIGO_PROYECTO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FECHA_CREACION)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FECHA_EVALUACION)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FECHA_MODIFICACION)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DESCRIPCION)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DATOS_PRUEBA)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CONCLUSIONES)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MODULO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CREADO_POR)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ESTADO)
                </td>
                <td>
                    <a href="@Url.Action("Edit", "Planes", new { id = item.ID_PRUEBAS })">
                        <img src="~/Img/pencil.svg" />
                    </a>
                    &nbsp;&nbsp;|&nbsp;&nbsp;
                    <a href="@Url.Action("Delete", "Planes", new { id = item.ID_PRUEBAS })">
                        <img src="~/Img/trash.svg" />
                    </a>
                </td>
            </tr>
        }

    </table>
</div>